#!/bin/sh
echo "Docker"
rm -f /var/lib/pacman/sync/*
pacman -Syy
pacman --noconfirm -S git
pacman --noconfirm -S docker-compose
pacman --noconfirm -S docker
systemctl start docker.service
systemctl enable docker.service

echo "Clone Source"
git clone https://github.com/code-SL/tidal-connect-docker
cd /tmp
wget https://raw.githubusercontent.com/lovehifi/tidal-raudio-pi4/main/entrypoint.sh
chmod -R 755 /tmp/entrypoint.sh
cp -f /tmp/entrypoint.sh /root/tidal-connect-docker/Docker/
cd /root/tidal-connect-docker
wget https://raw.githubusercontent.com/lovehifi/tidal-raudio-pi4/main/install.sh
chmod -R 755 install.sh

echo "Build Docker"
cd Docker
./build_docker.sh
cd ..
./install.sh
sleep 1

echo "Remove the text ipv6.disable=1 in /boot/cmdline.txt"
cp /boot/cmdline.txt /boot/cmdline.txt.backup && sed -i '0,/ipv6.disable=1/{s/ipv6.disable=1//}' /boot/cmdline.txt
sleep 1

if grep -q "dtparam=audio=on" /boot/config.txt; then
sudo sed -i '/dtparam=audio=on/d' /boot/config.txt
else
echo "No dtparam=audio=on"
fi

echo "Off the sound onboard"
grep -q "dtparam=audio=off" /boot/config.txt
if [ $? -eq 0 ]; then
echo "onboard off"
else
echo "dtparam=audio=off" | sudo tee -a /boot/config.txt
echo "onboard to off"
fi
reboot

